/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Controller;
import Model.Topic;
import java.util.ArrayList;
import java.util.Collection;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import Model.Experiencia;

/**
 *
 * @author chial
 */
public class AltaPostulanteS extends javax.swing.JFrame {

    /**
     * Creates new form AltaPostulanteS
     */
    public AltaPostulanteS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFrame = new javax.swing.JLabel();
        jLabelTema = new javax.swing.JLabel();
        jLabelNivel = new javax.swing.JLabel();
        jLabelExperiencia = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jSpinnerNivel = new javax.swing.JSpinner();
        jButtonAgregar = new javax.swing.JButton();
        jComboBoxTema = new javax.swing.JComboBox<>();
        jScrollPaneExperiencia = new javax.swing.JScrollPane();
        jListExperiencia = new javax.swing.JList<>();
        jSeparator = new javax.swing.JSeparator();
        jErrorExperiencia = new javax.swing.JLabel();
        jErrorTemaNivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta Postulante");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(374, 247));
        setResizable(false);
        setSize(new java.awt.Dimension(374, 280));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelFrame.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFrame.setLabelFor(this);
        jLabelFrame.setText("Experiencia");

        jLabelTema.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTema.setText("Tema");

        jLabelNivel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNivel.setText("Nivel");

        jLabelExperiencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelExperiencia.setText("Experiencia");

        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegistrarMouseClicked(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseClicked(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarMouseClicked(evt);
            }
        });

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarMouseClicked(evt);
            }
        });

        jScrollPaneExperiencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        jListExperiencia.setBackground(new java.awt.Color(236, 236, 236));
        jScrollPaneExperiencia.setViewportView(jListExperiencia);

        jErrorExperiencia.setForeground(new java.awt.Color(255, 0, 0));
        jErrorExperiencia.setText(" ");

        jErrorTemaNivel.setForeground(new java.awt.Color(255, 0, 0));
        jErrorTemaNivel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 143, Short.MAX_VALUE)
                .addComponent(jLabelFrame)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegistrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelExperiencia)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jErrorExperiencia)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPaneExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNivel)
                            .addComponent(jLabelTema))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jErrorTemaNivel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinnerNivel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAgregar))
                            .addComponent(jComboBoxTema, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTema)
                    .addComponent(jComboBoxTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNivel)
                    .addComponent(jSpinnerNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar))
                .addGap(0, 0, 0)
                .addComponent(jErrorTemaNivel)
                .addGap(2, 2, 2)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelExperiencia)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminar)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addComponent(jScrollPaneExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jErrorExperiencia)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getContentPane().setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_formWindowOpened

    private void jButtonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelarMouseClicked
        this.setVisible(false);
        Controller.initAltaPostulante(false);
    }//GEN-LAST:event_jButtonCancelarMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Controller.disposeAltaPostulante();
        Controller.initMenuPostulante();
    }//GEN-LAST:event_formWindowClosed

    private void jButtonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarMouseClicked
        boolean experienciaOK = this.modelo.getSize() >= 1;
        if (experienciaOK) {
            Object[] experienciaE = this.modelo.toArray();
            Experiencia[] experiencia = new Experiencia[experienciaE.length];

            for (int i = 0; i < experiencia.length; i++) {
                experiencia[i] = (Experiencia) experienciaE[i];
            }

            Controller.addPostulante(
                    Controller.getPostulanteNombre(),
                    Controller.getPostulanteCedula(),
                    Controller.getPostulanteDireccion(),
                    Controller.getPostulanteTelefono(),
                    Controller.getPostulanteMail(),
                    Controller.getPostulanteLinkedin(),
                    Controller.getPostulanteFormato(),
                    experiencia
            );
            this.dispose();
        } else {
            this.jErrorExperiencia.setText("Tiene que agregar un tema");
        }
    }//GEN-LAST:event_jButtonRegistrarMouseClicked

    private void jButtonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarMouseClicked
        this.jErrorExperiencia.setText(" ");
        int nivel = (int) this.jSpinnerNivel.getValue();
        Topic tema = (Topic) jComboBoxTema.getSelectedItem();
        if (nivel < 1 || nivel > 10) {
            this.jErrorTemaNivel.setText("Nivel 1 - 10");
        } else if (tema == null) {
            this.jErrorTemaNivel.setText("Ningun tema seleccionado");
        } else {
            this.jErrorTemaNivel.setText(" ");
            boolean isThere = false;
            Experiencia there = new Experiencia(nivel, tema);
            if (!this.modelo.contains(there) || this.modelo.isEmpty()) {
                this.modelo.addElement(new Experiencia(nivel, tema));
            } else {
                this.modelo.remove(this.modelo.indexOf(there));
                this.modelo.addElement(there);
            }
            this.jListExperiencia.setModel(this.modelo);
        }

    }//GEN-LAST:event_jButtonAgregarMouseClicked

    private void jButtonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarMouseClicked
        this.jErrorExperiencia.setText(" ");
        int index = this.jListExperiencia.getSelectedIndex();
        if (index != -1) {
            this.modelo.remove(index);
            this.jListExperiencia.setModel(this.modelo);
        } else {
            this.jErrorExperiencia.setText("Selecione una de las opciones");
        }
    }//GEN-LAST:event_jButtonEliminarMouseClicked

    public void reset() {
        this.jListExperiencia.setListData(new Experiencia[0]);
        this.jSpinnerNivel.setValue(0);
        this.jComboBoxTema.removeAllItems();
        this.jErrorExperiencia.setText(" ");
        this.modelo = new DefaultListModel<Experiencia>();
        this.jListExperiencia.setModel(this.modelo);
    }

    public void set(ArrayList<Topic> topicList) {
        DefaultComboBoxModel<Topic> temaModelo = new DefaultComboBoxModel<>();
        temaModelo.addAll((Collection<Topic>) topicList);
        this.jComboBoxTema.setModel(temaModelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox<Topic> jComboBoxTema;
    private javax.swing.JLabel jErrorExperiencia;
    private javax.swing.JLabel jErrorTemaNivel;
    private javax.swing.JLabel jLabelExperiencia;
    private javax.swing.JLabel jLabelFrame;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JLabel jLabelTema;
    private javax.swing.JList<Experiencia> jListExperiencia;
    private javax.swing.JScrollPane jScrollPaneExperiencia;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JSpinner jSpinnerNivel;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel<Experiencia> modelo = new DefaultListModel<Experiencia>();

}
