/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Controller;
import Model.Postulante;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.DefaultListModel;

/**
 *
 * @author chial
 */
public class BajaPostulante extends javax.swing.JFrame {

    /**
     * Creates new form BajaPostulante
     */
    public BajaPostulante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBajaPostulante = new javax.swing.JLabel();
        jButtonAtras = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        jScrollPanePostulante = new javax.swing.JScrollPane();
        jListPostulante = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baja Postulante");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelBajaPostulante.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelBajaPostulante.setLabelFor(this);
        jLabelBajaPostulante.setText("Baja de Postulante");

        jButtonAtras.setText("Atras");
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseClicked(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel.setText("Doble Click para Eliminar");

        jScrollPanePostulante.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        jListPostulante.setBackground(new java.awt.Color(236, 236, 236));
        jListPostulante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPostulanteMouseClicked(evt);
            }
        });
        jScrollPanePostulante.setViewportView(jListPostulante);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jButtonAtras)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPanePostulante)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabelBajaPostulante)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBajaPostulante)
                .addGap(1, 1, 1)
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPanePostulante, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAtras)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getContentPane().setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_formWindowOpened

    private void jButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseClicked
        this.dispose();
    }//GEN-LAST:event_jButtonAtrasMouseClicked

    public void reset() {
        this.modelo = new DefaultListModel();
        this.jListPostulante.setModel(modelo);
    }

    public void set(ArrayList<Postulante> postulantes) {
        this.modelo.addAll((Collection<Postulante>) postulantes);
        this.jListPostulante.setModel(this.modelo);
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Controller.initMenuPostulante();
    }//GEN-LAST:event_formWindowClosed

    private void jListPostulanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPostulanteMouseClicked
        int clicks = evt.getClickCount();
        if (clicks == 2) {
            Postulante postulante = this.jListPostulante.getSelectedValue();
            Controller.bajaPostulante(postulante);
            this.modelo.removeElement(postulante);
            this.jListPostulante.setModel(this.modelo);
        }
    }//GEN-LAST:event_jListPostulanteMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabelBajaPostulante;
    private javax.swing.JList<Postulante> jListPostulante;
    private javax.swing.JScrollPane jScrollPanePostulante;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel<Postulante> modelo;
}
