package View;

import Controller.Controlador;
import Model.Experiencia;
import Model.Postulante;
import Model.Puesto;
import Model.Tema;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.DefaultListModel;

/**
 *
 * @author Pedro Chialanza (302782)
 * @author Leandro Meneses (305998)
 */
public class ConsultaTematica extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaTematica
     */
    public ConsultaTematica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel = new javax.swing.JLabel();
        jScrollPaneTematica = new javax.swing.JScrollPane();
        jListTematicas = new javax.swing.JList<>();
        jLabelCantPostulantes = new javax.swing.JLabel();
        jLabelCantPuestos = new javax.swing.JLabel();
        jButtonAtras = new javax.swing.JButton();
        jTextFieldCantPostulantes = new javax.swing.JTextField();
        jTextFieldCantPuestos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel.setText("Consulta por Tematica");

        jScrollPaneTematica.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        jListTematicas.setBackground(new java.awt.Color(236, 236, 236));
        jListTematicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListTematicasMouseClicked(evt);
            }
        });
        jScrollPaneTematica.setViewportView(jListTematicas);

        jLabelCantPostulantes.setText("Postultantes con mayor nivel a 5:");

        jLabelCantPuestos.setText("Cantidad de puestos:");

        jButtonAtras.setText("Atras");
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseClicked(evt);
            }
        });

        jTextFieldCantPostulantes.setEditable(false);
        jTextFieldCantPostulantes.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldCantPostulantes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jTextFieldCantPostulantes.setFocusable(false);

        jTextFieldCantPuestos.setEditable(false);
        jTextFieldCantPuestos.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldCantPuestos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jTextFieldCantPuestos.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPaneTematica, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCantPostulantes)
                                    .addComponent(jLabelCantPuestos)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldCantPuestos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                        .addComponent(jTextFieldCantPostulantes, javax.swing.GroupLayout.Alignment.LEADING))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCantPostulantes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCantPostulantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabelCantPuestos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCantPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAtras))
                    .addComponent(jScrollPaneTematica, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getContentPane().setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_formWindowOpened

    private void jButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseClicked
        this.dispose();
    }//GEN-LAST:event_jButtonAtrasMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Controlador.initMenuTematica();
    }//GEN-LAST:event_formWindowClosed

    private void jListTematicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTematicasMouseClicked
        Tema seleccionado = this.jListTematicas.getSelectedValue();

        ArrayList<Puesto> puestos = Controlador.getPuestos();

        int contador = 0;

        for (int i = 0; i < puestos.size(); i++) {
            Tema[] temas = puestos.get(i).getTemasRequeridos();
            for (int j = 0; j < temas.length; j++) {
                if (temas[j] == seleccionado) {
                    contador++;
                }
            }
        }

        this.jTextFieldCantPuestos.setText(contador + "");

        ArrayList<Postulante> postulantes = Controlador.getPostulantes();

        int contadorNivel = 0;

        for (int i = 0; i < postulantes.size(); i++) {
            Experiencia[] temas = postulantes.get(i).getExperiencia();
            for (int j = 0; j < temas.length; j++) {
                if (temas[j].getTema() == seleccionado && temas[j].getNivel() > 5) {
                    contadorNivel++;
                }
            }
        }

        this.jTextFieldCantPostulantes.setText(contadorNivel + "");
    }//GEN-LAST:event_jListTematicasMouseClicked

    public void reset() {
        this.modelo = new DefaultListModel<Tema>();
        this.jListTematicas.setModel(modelo);
        this.jTextFieldCantPostulantes.setText("");
        this.jTextFieldCantPuestos.setText("");
    }

    public void set(ArrayList<Tema> tematicas) {
        this.modelo.addAll((Collection<Tema>) tematicas);
        this.jListTematicas.setModel(this.modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabelCantPostulantes;
    private javax.swing.JLabel jLabelCantPuestos;
    private javax.swing.JList<Tema> jListTematicas;
    private javax.swing.JScrollPane jScrollPaneTematica;
    private javax.swing.JTextField jTextFieldCantPostulantes;
    private javax.swing.JTextField jTextFieldCantPuestos;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel<Tema> modelo;
}
