/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Controller;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author chial
 */
public class HistorialPostulante extends javax.swing.JFrame {

    /**
     * Creates new form HistorialPostulante
     */
    public HistorialPostulante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPostulantes = new javax.swing.JLabel();
        jScrollPanePostulantes = new javax.swing.JScrollPane();
        jListPostulantes = new javax.swing.JList<>();
        jLabelBuscar = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonResetear = new javax.swing.JButton();
        jScrollPaneReferencia = new javax.swing.JScrollPane();
        jTableReferencia = new javax.swing.JTable();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        jLabelLinkedin = new javax.swing.JLabel();
        jLabelFormato = new javax.swing.JLabel();
        jLabelExperiencia = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldLinkedin = new javax.swing.JTextField();
        jTextFieldFormato = new javax.swing.JTextField();
        jTextFieldMail = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelFrame = new javax.swing.JLabel();
        jScrollPaneExperiencia = new javax.swing.JScrollPane();
        jListExperiencia = new javax.swing.JList<>();
        jSeparator = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historial Postulante");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1252, 1021));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1252, 1021));
        setMinimumSize(new java.awt.Dimension(626, 510));
        setName("Historial Postulante"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1044, 851));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelPostulantes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPostulantes.setLabelFor(jListPostulantes);
        jLabelPostulantes.setText("Postulantes:");
        jLabelPostulantes.setName("JLabelPostulante"); // NOI18N

        jScrollPanePostulantes.setBorder(null);
        jScrollPanePostulantes.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        jListPostulantes.setBackground(new java.awt.Color(236, 236, 236));
        jListPostulantes.setPreferredSize(new java.awt.Dimension(330, 303));
        jScrollPanePostulantes.setViewportView(jListPostulantes);
        jListPostulantes.getAccessibleContext().setAccessibleParent(jListPostulantes);

        jLabelBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBuscar.setLabelFor(jTextFieldBuscar);
        jLabelBuscar.setText("Buscar:");

        jTextFieldBuscar.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.lightGray));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setToolTipText("");

        jButtonResetear.setText("Resetear");

        jScrollPaneReferencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jScrollPaneReferencia.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        jTableReferencia.setBackground(new java.awt.Color(236, 236, 236));
        jTableReferencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nro", "Evaluador", "Puntaje", "Comentario"
            }
        ));
        jTableReferencia.setColumnSelectionAllowed(true);
        jTableReferencia.setEnabled(false);
        jTableReferencia.getColumnModel().getColumn(0).setPreferredWidth(50);
        jScrollPaneReferencia.setViewportView(jTableReferencia);

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNombre.setLabelFor(jTextFieldNombre);
        jLabelNombre.setText("Nombre:");
        jLabelNombre.setName("jLabelNombre"); // NOI18N

        jLabelCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCedula.setLabelFor(jTextFieldCedula);
        jLabelCedula.setText("Cédula:");

        jLabelDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDireccion.setLabelFor(jTextFieldDireccion);
        jLabelDireccion.setText("Dirección:");

        jLabelTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTelefono.setLabelFor(jTextFieldTelefono);
        jLabelTelefono.setText("Teléfono:");

        jLabelMail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMail.setLabelFor(jTextFieldMail);
        jLabelMail.setText("Mail:");

        jLabelLinkedin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelLinkedin.setLabelFor(jTextFieldLinkedin);
        jLabelLinkedin.setText("Linkedin:");

        jLabelFormato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFormato.setLabelFor(jTextFieldFormato);
        jLabelFormato.setText("Formato:");

        jLabelExperiencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelExperiencia.setLabelFor(jLabelExperiencia);
        jLabelExperiencia.setText("Experiencia:");

        jTextFieldNombre.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jTextFieldNombre.setFocusable(false);
        jTextFieldNombre.setName("jTextFieldNombre"); // NOI18N

        jTextFieldLinkedin.setEditable(false);
        jTextFieldLinkedin.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldLinkedin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jTextFieldLinkedin.setFocusable(false);

        jTextFieldFormato.setEditable(false);
        jTextFieldFormato.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldFormato.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jTextFieldFormato.setFocusable(false);

        jTextFieldMail.setEditable(false);
        jTextFieldMail.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldMail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jTextFieldMail.setFocusable(false);

        jTextFieldDireccion.setEditable(false);
        jTextFieldDireccion.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldDireccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jTextFieldDireccion.setFocusable(false);

        jTextFieldCedula.setEditable(false);
        jTextFieldCedula.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldCedula.setActionCommand("<Not Set>");
        jTextFieldCedula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jTextFieldCedula.setFocusable(false);

        jTextFieldTelefono.setEditable(false);
        jTextFieldTelefono.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        jLabelFrame.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelFrame.setLabelFor(this);
        jLabelFrame.setText("Historial Postulante");

        jScrollPaneExperiencia.setBorder(null);
        jScrollPaneExperiencia.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        jListExperiencia.setBackground(new java.awt.Color(236, 236, 236));
        jScrollPaneExperiencia.setViewportView(jListExperiencia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPostulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPaneReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPanePostulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelCedula)
                                    .addComponent(jLabelDireccion))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNombre)
                                    .addComponent(jTextFieldCedula)
                                    .addComponent(jTextFieldDireccion)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTelefono)
                                    .addComponent(jLabelMail)
                                    .addComponent(jLabelLinkedin)
                                    .addComponent(jLabelFormato)
                                    .addComponent(jLabelExperiencia))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTelefono)
                                    .addComponent(jTextFieldMail)
                                    .addComponent(jTextFieldLinkedin)
                                    .addComponent(jTextFieldFormato)
                                    .addComponent(jScrollPaneExperiencia))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonResetear)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(417, 417, 417)
                .addComponent(jLabelFrame)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPostulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCedula)
                            .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDireccion)
                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTelefono)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMail)
                            .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLinkedin)
                            .addComponent(jTextFieldLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFormato)
                            .addComponent(jTextFieldFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelExperiencia)
                            .addComponent(jScrollPaneExperiencia)))
                    .addComponent(jScrollPanePostulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBuscar)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonResetear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelPostulantes.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getContentPane().setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Controller.initMenuPostulante();
    }//GEN-LAST:event_formWindowClosed

    public void reset() {
        this.jTextFieldCedula.setText("");
        this.jTextFieldDireccion.setText("");
        this.jTextFieldLinkedin.setText("");
        this.jTextFieldMail.setText("");
        this.jTextFieldNombre.setText("");
        this.jTextFieldTelefono.setText("");
        this.jTextFieldFormato.setText("");
        this.jListPostulantes.setListData(new String[0]);
        this.jListExperiencia.setListData(new String[0]);
        this.jTableReferencia.removeAll();
        this.jTextFieldBuscar.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonResetear;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelExperiencia;
    private javax.swing.JLabel jLabelFormato;
    private javax.swing.JLabel jLabelFrame;
    private javax.swing.JLabel jLabelLinkedin;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPostulantes;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JList<String> jListExperiencia;
    private javax.swing.JList<String> jListPostulantes;
    private javax.swing.JScrollPane jScrollPaneExperiencia;
    private javax.swing.JScrollPane jScrollPanePostulantes;
    private javax.swing.JScrollPane jScrollPaneReferencia;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JTable jTableReferencia;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldFormato;
    private javax.swing.JTextField jTextFieldLinkedin;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
