package View;

import Controller.Controlador;
import Model.CriterioCedula;
import Model.Entrevista;
import Model.Experiencia;
import Model.Postulante;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedro Chialanza (302782)
 * @author Leandro Meneses (305998)
 */
public class HistorialPostulante extends javax.swing.JFrame {

    /**
     * Creates new form HistorialPostulante
     */
    public HistorialPostulante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPostulantes = new javax.swing.JLabel();
        jScrollPanePostulantes = new javax.swing.JScrollPane();
        jListPostulantes = new javax.swing.JList<>();
        jLabelBuscar = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonResetear = new javax.swing.JButton();
        jScrollPaneReferencia = new javax.swing.JScrollPane();
        jTableReferencia = new javax.swing.JTable();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        jLabelLinkedin = new javax.swing.JLabel();
        jLabelFormato = new javax.swing.JLabel();
        jLabelExperiencia = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldLinkedin = new javax.swing.JTextField();
        jTextFieldFormato = new javax.swing.JTextField();
        jTextFieldMail = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelFrame = new javax.swing.JLabel();
        jScrollPaneExperiencia = new javax.swing.JScrollPane();
        jListExperiencia = new javax.swing.JList<>();
        jSeparator = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historial Postulante");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1252, 1021));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1252, 1021));
        setMinimumSize(new java.awt.Dimension(626, 510));
        setName("Historial Postulante"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1044, 851));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelPostulantes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPostulantes.setLabelFor(jListPostulantes);
        jLabelPostulantes.setText("Postulantes:");
        jLabelPostulantes.setName("JLabelPostulante"); // NOI18N

        jScrollPanePostulantes.setBorder(null);
        jScrollPanePostulantes.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        jListPostulantes.setBackground(new java.awt.Color(236, 236, 236));
        jListPostulantes.setPreferredSize(new java.awt.Dimension(330, 303));
        jListPostulantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPostulantesMouseClicked(evt);
            }
        });
        jScrollPanePostulantes.setViewportView(jListPostulantes);
        jListPostulantes.getAccessibleContext().setAccessibleParent(jListPostulantes);

        jLabelBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBuscar.setLabelFor(jTextFieldBuscar);
        jLabelBuscar.setText("Buscar:");

        jTextFieldBuscar.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.lightGray));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setToolTipText("");
        jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseClicked(evt);
            }
        });

        jButtonResetear.setText("Resetear");
        jButtonResetear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonResetearMouseClicked(evt);
            }
        });

        jScrollPaneReferencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jScrollPaneReferencia.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        jTableReferencia.setBackground(new java.awt.Color(236, 236, 236));
        jTableReferencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro", "Evaluador", "Puntaje", "Comentario"
            }
        ));
        jTableReferencia.setColumnSelectionAllowed(true);
        jTableReferencia.setEnabled(false);
        jTableReferencia.getColumnModel().getColumn(0).setPreferredWidth(50);
        jScrollPaneReferencia.setViewportView(jTableReferencia);

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNombre.setLabelFor(jTextFieldNombre);
        jLabelNombre.setText("Nombre:");
        jLabelNombre.setName("jLabelNombre"); // NOI18N

        jLabelCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCedula.setLabelFor(jTextFieldCedula);
        jLabelCedula.setText("Cédula:");

        jLabelDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDireccion.setLabelFor(jTextFieldDireccion);
        jLabelDireccion.setText("Dirección:");

        jLabelTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTelefono.setLabelFor(jTextFieldTelefono);
        jLabelTelefono.setText("Teléfono:");

        jLabelMail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMail.setLabelFor(jTextFieldMail);
        jLabelMail.setText("Mail:");

        jLabelLinkedin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelLinkedin.setLabelFor(jTextFieldLinkedin);
        jLabelLinkedin.setText("Linkedin:");

        jLabelFormato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFormato.setLabelFor(jTextFieldFormato);
        jLabelFormato.setText("Formato:");

        jLabelExperiencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelExperiencia.setLabelFor(jLabelExperiencia);
        jLabelExperiencia.setText("Experiencia:");

        jTextFieldNombre.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jTextFieldNombre.setFocusable(false);
        jTextFieldNombre.setName("jTextFieldNombre"); // NOI18N

        jTextFieldLinkedin.setEditable(false);
        jTextFieldLinkedin.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldLinkedin.setForeground(new java.awt.Color(0, 0, 255));
        jTextFieldLinkedin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jTextFieldLinkedin.setFocusable(false);
        jTextFieldLinkedin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldLinkedinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldLinkedinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldLinkedinMouseExited(evt);
            }
        });

        jTextFieldFormato.setEditable(false);
        jTextFieldFormato.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldFormato.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jTextFieldFormato.setFocusable(false);

        jTextFieldMail.setEditable(false);
        jTextFieldMail.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldMail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jTextFieldMail.setFocusable(false);

        jTextFieldDireccion.setEditable(false);
        jTextFieldDireccion.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldDireccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jTextFieldDireccion.setFocusable(false);

        jTextFieldCedula.setEditable(false);
        jTextFieldCedula.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldCedula.setActionCommand("<Not Set>");
        jTextFieldCedula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jTextFieldCedula.setFocusable(false);

        jTextFieldTelefono.setEditable(false);
        jTextFieldTelefono.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        jLabelFrame.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelFrame.setLabelFor(this);
        jLabelFrame.setText("Historial Postulante");

        jScrollPaneExperiencia.setBorder(null);
        jScrollPaneExperiencia.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        jListExperiencia.setBackground(new java.awt.Color(236, 236, 236));
        jScrollPaneExperiencia.setViewportView(jListExperiencia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPostulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPaneReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPanePostulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelCedula)
                                    .addComponent(jLabelDireccion))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNombre)
                                    .addComponent(jTextFieldCedula)
                                    .addComponent(jTextFieldDireccion)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTelefono)
                                    .addComponent(jLabelMail)
                                    .addComponent(jLabelLinkedin)
                                    .addComponent(jLabelFormato)
                                    .addComponent(jLabelExperiencia))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTelefono)
                                    .addComponent(jTextFieldMail)
                                    .addComponent(jTextFieldLinkedin)
                                    .addComponent(jTextFieldFormato)
                                    .addComponent(jScrollPaneExperiencia))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonResetear)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(417, 417, 417)
                .addComponent(jLabelFrame)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPostulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCedula)
                            .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDireccion)
                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTelefono)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMail)
                            .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLinkedin)
                            .addComponent(jTextFieldLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFormato)
                            .addComponent(jTextFieldFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelExperiencia)
                            .addComponent(jScrollPaneExperiencia)))
                    .addComponent(jScrollPanePostulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBuscar)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonResetear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jLabelPostulantes.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getContentPane().setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Controlador.initMenuPostulante();
    }//GEN-LAST:event_formWindowClosed

    private void jListPostulantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPostulantesMouseClicked
        Postulante postulante = this.jListPostulantes.getSelectedValue();
        this.jTextFieldNombre.setText(postulante.getNombre());
        this.jTextFieldCedula.setText(postulante.getCedula());
        this.jTextFieldDireccion.setText(postulante.getDireccion());
        this.jTextFieldTelefono.setText(postulante.getTelefono());
        this.jTextFieldMail.setText(postulante.getMail());
        this.jTextFieldLinkedin.setText(postulante.getLinkedin());
        this.jTextFieldFormato.setText(postulante.getCedula());
        this.jListExperiencia.setListData(postulante.getExperiencia());

        ArrayList<Entrevista> entrevistas = postulante.getEntrevistas();

        Object[][] rows = new Object[entrevistas.size()][4];

        for (int i = 0; i < entrevistas.size(); i++) {
            Entrevista entrevista = entrevistas.get(i);
            rows[i][0] = i + 1;
            rows[i][1] = entrevista.getEntrevistador();
            rows[i][2] = entrevista.getPuntaje();
            rows[i][3] = entrevista.getComentario();
        }

        this.model.setDataVector(rows, columns);
    }//GEN-LAST:event_jListPostulantesMouseClicked

    private void jTextFieldLinkedinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldLinkedinMouseClicked
        String link = this.jTextFieldLinkedin.getText();
        if (!link.equals("")) {
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                try {
                    Desktop.getDesktop().browse(new URI(link));
                } catch (URISyntaxException ex) {
                    JOptionPane.showMessageDialog(this, "Linkedin link no es un link valido");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Fallo en abrir navegador o no se encontro su navogador predeterminado");
                }
            }
        }
    }//GEN-LAST:event_jTextFieldLinkedinMouseClicked

    private void jTextFieldLinkedinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldLinkedinMouseEntered
        this.getRootPane().setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.jTextFieldLinkedin.setForeground(new Color(76, 40, 130));
    }//GEN-LAST:event_jTextFieldLinkedinMouseEntered

    private void jTextFieldLinkedinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldLinkedinMouseExited
        this.getRootPane().setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        this.jTextFieldLinkedin.setForeground(new Color(0, 0, 255));
    }//GEN-LAST:event_jTextFieldLinkedinMouseExited

    private void jButtonResetearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetearMouseClicked
        this.jTextFieldBuscar.setText("");
        Postulante postulante = this.jListPostulantes.getSelectedValue();
        ArrayList<Entrevista> entrevistas = postulante.getEntrevistas();

        Object[][] rows = new Object[entrevistas.size()][4];

        for (int i = 0; i < entrevistas.size(); i++) {
            Entrevista entrevista = entrevistas.get(i);
            rows[i][0] = i + 1;
            rows[i][1] = entrevista.getEntrevistador();
            rows[i][2] = entrevista.getPuntaje();
            rows[i][3] = entrevista.getComentario();
        }

        this.model.setDataVector(rows, columns);

    }//GEN-LAST:event_jButtonResetearMouseClicked

    private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseClicked
        String buscador = this.jTextFieldBuscar.getText();
        if (!buscador.equals("") && this.model.getRowCount() > 0) {
            Postulante postulante = this.jListPostulantes.getSelectedValue();
            ArrayList<Entrevista> entrevistas = postulante.getEntrevistas();

            ArrayList<Object[]> rows = new ArrayList<Object[]>();
            int defase = 0;

            for (int i = 0; i < entrevistas.size(); i++) {
                Entrevista entrevista = entrevistas.get(i);
                String comentario = entrevista.getComentario();
                Object[] row = new Object[4];
                if (comentario.indexOf(buscador) != -1) {
                    row[0] = i + 1 - defase;
                    row[1] = entrevista.getEntrevistador();
                    row[2] = entrevista.getPuntaje();
                    row[3] = "<html>" + comentario.replace(buscador, "<span style=\"color: red;\">" + buscador + "</span>") + "</html>";
                    rows.add(row);
                } else {
                    defase++;
                }
            }

            Object[][] rowsCasting = new Object[rows.size()][4];
            for (int i = 0; i < rows.size(); i++) {
                rowsCasting[i] = (Object[]) rows.get(i);
            }

            this.model.setDataVector(rowsCasting, columns);
        }
    }//GEN-LAST:event_jButtonBuscarMouseClicked

    public void reset() {
        this.jTextFieldCedula.setText("");
        this.jTextFieldDireccion.setText("");
        this.jTextFieldLinkedin.setText("");
        this.jTextFieldMail.setText("");
        this.jTextFieldNombre.setText("");
        this.jTextFieldTelefono.setText("");
        this.jTextFieldFormato.setText("");
        this.jListPostulantes.setListData(new Postulante[0]);
        this.jListExperiencia.setListData(new Experiencia[0]);
        this.jTableReferencia.removeAll();
        this.jTextFieldBuscar.setText("");
        this.model = new DefaultTableModel();
        this.model.setColumnIdentifiers(this.columns);
        this.jTableReferencia.setModel(this.model);
    }

    public void set(ArrayList<Postulante> postulantes) {
        Collections.sort(postulantes, new CriterioCedula());
        DefaultListModel<Postulante> modelo = new DefaultListModel<Postulante>();
        modelo.addAll((Collection<Postulante>) postulantes);
        this.jListPostulantes.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonResetear;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelExperiencia;
    private javax.swing.JLabel jLabelFormato;
    private javax.swing.JLabel jLabelFrame;
    private javax.swing.JLabel jLabelLinkedin;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPostulantes;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JList<Experiencia> jListExperiencia;
    private javax.swing.JList<Postulante> jListPostulantes;
    private javax.swing.JScrollPane jScrollPaneExperiencia;
    private javax.swing.JScrollPane jScrollPanePostulantes;
    private javax.swing.JScrollPane jScrollPaneReferencia;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JTable jTableReferencia;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldFormato;
    private javax.swing.JTextField jTextFieldLinkedin;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel model = new DefaultTableModel();
    private Object[] columns = {"Nro", "Evaluador", "Puntaje", "Comentario"};
}
