/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author chial
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMenu = new javax.swing.JLabel();
        jButtonRegistroTematica = new javax.swing.JButton();
        jButtonAltaPostulante = new javax.swing.JButton();
        jButtonConsultaPuesto = new javax.swing.JButton();
        jButtonHistoriaPostulante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelMenu.setText("Menu");

        jButtonRegistroTematica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonRegistroTematica.setText("Registro de Tematica");

        jButtonAltaPostulante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAltaPostulante.setText("Alta Postulante");

        jButtonConsultaPuesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonConsultaPuesto.setText("Consulta de Puesto");

        jButtonHistoriaPostulante.setText("Historial de Postulante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonHistoriaPostulante)
                    .addComponent(jButtonConsultaPuesto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(111, 111, 111)
                            .addComponent(jLabelMenu))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(jButtonRegistroTematica))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(jButtonAltaPostulante))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMenu)
                .addGap(34, 34, 34)
                .addComponent(jButtonRegistroTematica)
                .addGap(18, 18, 18)
                .addComponent(jButtonAltaPostulante)
                .addGap(18, 18, 18)
                .addComponent(jButtonConsultaPuesto)
                .addGap(18, 18, 18)
                .addComponent(jButtonHistoriaPostulante)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getContentPane().setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAltaPostulante;
    private javax.swing.JButton jButtonConsultaPuesto;
    private javax.swing.JButton jButtonHistoriaPostulante;
    private javax.swing.JButton jButtonRegistroTematica;
    private javax.swing.JLabel jLabelMenu;
    // End of variables declaration//GEN-END:variables
}
