/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Controller;

/**
 *
 * @author chial
 */
public class MenuPostulante extends javax.swing.JFrame {

    /**
     * Creates new form MenuTematica
     */
    public MenuPostulante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMenu = new javax.swing.JLabel();
        jButtonAltaPostulante = new javax.swing.JButton();
        jButtonBajaPostulante = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jButtonHistorialPostulante = new javax.swing.JButton();
        jButtonIngresoEntrevista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Puesto");
        setAlwaysOnTop(true);
        setFocusableWindowState(false);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabelMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu.setLabelFor(this);
        jLabelMenu.setText("Menu Postulante");

        jButtonAltaPostulante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAltaPostulante.setText("Alta de Postulante");

        jButtonBajaPostulante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonBajaPostulante.setText("Baja de Postulante");

        jButtonAtras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAtras.setText("Atras");
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseClicked(evt);
            }
        });

        jButtonHistorialPostulante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonHistorialPostulante.setText("Historial Postulante");

        jButtonIngresoEntrevista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonIngresoEntrevista.setText("Ingreso de Entrevista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBajaPostulante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAltaPostulante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonHistorialPostulante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIngresoEntrevista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMenu)
                .addGap(18, 18, 18)
                .addComponent(jButtonAltaPostulante)
                .addGap(18, 18, 18)
                .addComponent(jButtonBajaPostulante)
                .addGap(18, 18, 18)
                .addComponent(jButtonHistorialPostulante)
                .addGap(18, 18, 18)
                .addComponent(jButtonIngresoEntrevista)
                .addGap(18, 18, 18)
                .addComponent(jButtonAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Controller.init();
    }//GEN-LAST:event_formWindowClosed

    private void jButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseClicked
        this.setVisible(false);
        Controller.init();
    }//GEN-LAST:event_jButtonAtrasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAltaPostulante;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonBajaPostulante;
    private javax.swing.JButton jButtonHistorialPostulante;
    private javax.swing.JButton jButtonIngresoEntrevista;
    private javax.swing.JLabel jLabelMenu;
    // End of variables declaration//GEN-END:variables
}
