package View;

import Controller.Controlador;
import Model.Tema;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.DefaultListModel;

/**
 *
 * @author Pedro Chialanza (302782)
 * @author Leandro Meneses (305998)
 */
public class RegistroPuesto extends javax.swing.JFrame {

    /**
     * Creates new form RegistroPuesto
     */
    public RegistroPuesto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        jLabelRegistroPuesto = new javax.swing.JLabel();
        jButtonAtras = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelTema = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jRadioButtonRemoto = new javax.swing.JRadioButton();
        jRadioButtonPresencial = new javax.swing.JRadioButton();
        jRadioButtonMixto = new javax.swing.JRadioButton();
        jScrollPaneTema = new javax.swing.JScrollPane();
        jListTema = new javax.swing.JList<>();
        jScrollPaneTemaSelected = new javax.swing.JScrollPane();
        jListTemaSelected = new javax.swing.JList<>();
        jErrorNombre = new javax.swing.JLabel();
        jErrorTipo = new javax.swing.JLabel();
        jErrorTema = new javax.swing.JLabel();
        jButtomRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelRegistroPuesto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelRegistroPuesto.setText("Registro de Puesto ");

        jButtonAtras.setText("Atras");
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseClicked(evt);
            }
        });

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabelTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTipo.setText("Tipo:");

        jLabelTema.setText("Tema:");

        jTextFieldNombre.setBackground(new java.awt.Color(236, 236, 236));
        jTextFieldNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.lightGray));
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyReleased(evt);
            }
        });

        jRadioButtonRemoto.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupTipo.add(jRadioButtonRemoto);
        jRadioButtonRemoto.setText("Remoto");
        jRadioButtonRemoto.setToolTipText("");
        jRadioButtonRemoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonRemotoMouseClicked(evt);
            }
        });

        jRadioButtonPresencial.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupTipo.add(jRadioButtonPresencial);
        jRadioButtonPresencial.setText("Presencial");
        jRadioButtonPresencial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonPresencialMouseClicked(evt);
            }
        });

        jRadioButtonMixto.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupTipo.add(jRadioButtonMixto);
        jRadioButtonMixto.setText("Mixto");
        jRadioButtonMixto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonMixtoMouseClicked(evt);
            }
        });

        jScrollPaneTema.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        jListTema.setBackground(new java.awt.Color(236, 236, 236));
        jListTema.setToolTipText("Doble click para agregar");
        jListTema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListTemaMouseClicked(evt);
            }
        });
        jScrollPaneTema.setViewportView(jListTema);

        jScrollPaneTemaSelected.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        jListTemaSelected.setBackground(new java.awt.Color(236, 236, 236));
        jListTemaSelected.setToolTipText("Doble click para Eliminar");
        jListTemaSelected.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListTemaSelectedMouseClicked(evt);
            }
        });
        jScrollPaneTemaSelected.setViewportView(jListTemaSelected);

        jErrorNombre.setForeground(new java.awt.Color(255, 0, 0));
        jErrorNombre.setText(" ");

        jErrorTipo.setForeground(new java.awt.Color(255, 0, 0));
        jErrorTipo.setText(" ");

        jErrorTema.setForeground(new java.awt.Color(255, 0, 0));
        jErrorTema.setText(" ");

        jButtomRegistrar.setText("Registrar");
        jButtomRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtomRegistrarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setText("Doble Click para agregar y eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelRegistroPuesto)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelTipo)
                            .addComponent(jLabelTema))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jErrorNombre)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldNombre)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonRemoto)
                                .addGap(57, 57, 57)
                                .addComponent(jRadioButtonPresencial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonMixto))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 14, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jErrorTipo)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jErrorTema, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jScrollPaneTema, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPaneTemaSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jButtonAtras)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1)
                                            .addGap(14, 14, 14)
                                            .addComponent(jButtomRegistrar))))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegistroPuesto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jErrorNombre)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo)
                    .addComponent(jRadioButtonRemoto)
                    .addComponent(jRadioButtonPresencial)
                    .addComponent(jRadioButtonMixto))
                .addGap(0, 0, 0)
                .addComponent(jErrorTipo)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneTemaSelected)
                    .addComponent(jScrollPaneTema)
                    .addComponent(jLabelTema))
                .addGap(0, 0, 0)
                .addComponent(jErrorTema)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAtras)
                    .addComponent(jButtomRegistrar)
                    .addComponent(jLabel1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getContentPane().setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Controlador.initMenuPuesto();
    }//GEN-LAST:event_formWindowClosed

    private void jButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseClicked
        this.dispose();
    }//GEN-LAST:event_jButtonAtrasMouseClicked

    private void jButtomRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtomRegistrarMouseClicked
        boolean nombreOK = this.verifyNombre(this.jTextFieldNombre.getText());
        boolean tipoOK = this.buttonGroupTipo.getSelection() != null;
        boolean temaOK = this.jListTemaSelected.getModel().getSize() > 0;

        if (nombreOK && tipoOK && temaOK) {
            Object[] experienciaE = this.modeloSelected.toArray();
            Tema[] topic = new Tema[experienciaE.length];

            for (int i = 0; i < topic.length; i++) {
                topic[i] = (Tema) experienciaE[i];
            }

            Controlador.addPuesto(this.jTextFieldNombre.getText(), this.getFormato(), topic);
            this.dispose();
        } else {
            this.jErrorTipo.setText(tipoOK ? " " : "Selecione una opcion");
            this.jErrorTema.setText(temaOK ? " " : "Seleccione un tema");

        }
    }//GEN-LAST:event_jButtomRegistrarMouseClicked

    public boolean verifyNombre(String nombre) {
        boolean nombreVacio = nombre.equals("");

        if (nombreVacio) {
            this.jErrorNombre.setText("No debe estar vacio");
        }
        String erorrMesage = Controlador.verifyNombrePuesto(nombre);
        this.jErrorNombre.setText(erorrMesage.equals("") ? " " : erorrMesage);

        return !nombreVacio && erorrMesage.equals("");
    }

    private void jRadioButtonRemotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonRemotoMouseClicked
        this.jErrorTipo.setText(" ");
    }//GEN-LAST:event_jRadioButtonRemotoMouseClicked

    private void jRadioButtonPresencialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonPresencialMouseClicked
        this.jErrorTipo.setText(" ");
    }//GEN-LAST:event_jRadioButtonPresencialMouseClicked

    private void jRadioButtonMixtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonMixtoMouseClicked
        this.jErrorTipo.setText(" ");
    }//GEN-LAST:event_jRadioButtonMixtoMouseClicked

    private void jTextFieldNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyReleased
        this.verifyNombre(this.jTextFieldNombre.getText());
    }//GEN-LAST:event_jTextFieldNombreKeyReleased

    private void jListTemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTemaMouseClicked
        if (evt.getClickCount() == 2) {
            evt.consume();
            int index = this.jListTema.getSelectedIndex();
            Tema selected = this.modelo.remove(index);
            this.modeloSelected.addElement(selected);
            this.jListTema.setModel(this.modelo);
            this.jListTemaSelected.setModel(this.modeloSelected);
        }
    }//GEN-LAST:event_jListTemaMouseClicked

    private void jListTemaSelectedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTemaSelectedMouseClicked
        if (evt.getClickCount() == 2) {
            evt.consume();
            int index = this.jListTemaSelected.getSelectedIndex();
            Tema selected = this.modeloSelected.remove(index);
            this.modelo.addElement(selected);
            this.jListTema.setModel(this.modelo);
            this.jListTemaSelected.setModel(this.modeloSelected);
        }
    }//GEN-LAST:event_jListTemaSelectedMouseClicked

    public void reset() {
        this.jTextFieldNombre.setText("");
        this.buttonGroupTipo.clearSelection();
        this.jListTema.setListData(new Tema[0]);
        this.jListTemaSelected.setListData(new Tema[0]);
        this.jErrorNombre.setText(" ");
        this.jErrorTema.setText(" ");
        this.jErrorTipo.setText(" ");
        this.modelo = new DefaultListModel<Tema>();
        this.jListTema.setModel(this.modelo);
        this.modeloSelected = new DefaultListModel<Tema>();
        this.jListTemaSelected.setModel(this.modeloSelected);
    }

    public void set(ArrayList<Tema> temaList) {
        this.modelo.addAll((Collection<Tema>) temaList);
        this.jListTema.setModel(this.modelo);
    }

    public String getFormato() {
        String out = "";

        for (Enumeration<AbstractButton> buttons = buttonGroupTipo.getElements(); buttons.hasMoreElements() && out.equals("");) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                out = button.getText();
            }
        }

        return out;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JButton jButtomRegistrar;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JLabel jErrorNombre;
    private javax.swing.JLabel jErrorTema;
    private javax.swing.JLabel jErrorTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelRegistroPuesto;
    private javax.swing.JLabel jLabelTema;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JList<Model.Tema> jListTema;
    private javax.swing.JList<Model.Tema> jListTemaSelected;
    private javax.swing.JRadioButton jRadioButtonMixto;
    private javax.swing.JRadioButton jRadioButtonPresencial;
    private javax.swing.JRadioButton jRadioButtonRemoto;
    private javax.swing.JScrollPane jScrollPaneTema;
    private javax.swing.JScrollPane jScrollPaneTemaSelected;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel<Tema> modeloSelected;
    private DefaultListModel<Tema> modelo;

}
